engine.name=hyo1

db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://172.17.0.3:5432/myapp_db
db.user=myuser
db.password=mypass

# Equal to node_group_id in sym_node_group table. Triggers and routers are assigned to groups
group.id=hyo-group-for-x
external.id=hyo1-id
instance.id=hyo1-instance

# URL where this node listens
sync.url=http://172.17.0.3:31415/sync/hyo1
# Accept registrations?
registration.enabled=false
# Where to registrate this node (empty if this is the first=root)
registration.url=http://172.17.0.2:31415/sync/lim1
# Register in registration.url at startup
#auto.registration=true

job.routing.period.time.ms=5000
job.push.period.time.ms=1000
job.pull.period.time.ms=1000

# Create tables if not exists in this node?
initial.load.create.first=true