apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
spec:
  containers:
    - name: container-demo
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: vol-demo
  volumes:
    - name: vol-demo
      persistentVolumeClaim:
        claimName: pvc-demo
