apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init-job
spec:
  template:
    spec:
      containers:
      - name: mysql-init
        image: mysql:8.0
        command:
        - /bin/bash
        - -c
        - |
          mysql -h $MYSQL_HOST -u $MYSQL_ROOT_USER -p$MYSQL_ROOT_PASSWORD < /docker-entrypoint-initdb.d/init.sql
        env:
        - name: MYSQL_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: app1-secrets
              key: db_user
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app1-secrets
              key: db_password
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: app1-config
              key: db_host
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-script
        configMap:
          name: mysql-init-script
      restartPolicy: Never
  backoffLimit: 4