engine.name=main

db.driver=com.mysql.jdbc.Driver
db.url=jdbc:mysql://127.0.0.1:3306/myapp_db?tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull
db.user=myuser
db.password=mypass

# Equal to node_group_id in sym_node_group table. Triggers and routers are assigned to groups
# The same group id for bidirectional sync
# Node group this node belongs to, which defines what it will sync with who.
# Must match the sym_node_group configuration in database.
group.id=main-group
# External ID for this node, which is any unique identifier you want to use.
external.id=main-id
instance.id=main-instance

# This node will contact the root node's sync.url to register itself.
# Leave blank to indicate this is the root node.
registration.url=
# URL where this node listens
sync.url=http://172.17.0.2:31415/sync/main
# Accept registrations?
registration.enabled=true
# Automatically register new nodes when they request it.
# If this is false, accept the registration requests using "symadmin open-registration" command.
auto.registration=true
# Automatically send an initial load to a node after it registers.
auto.reload=true

# Check sym_data and send data
job.routing.period.time.ms=5000
job.push.period.time.ms=2500
job.pull.period.time.ms=2500

# When this node sends an initial load of data to another node, first send table create scripts.
initial.load.create.first=true