engine.name=region2

db.driver=com.mysql.jdbc.Driver
db.url=jdbc:mysql://127.0.0.1:3306/myapp_db?tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull
db.user=myuser
db.password=mypass

# Equal to node_group_id in sym_node_group table. Triggers and routers are assigned to groups
# The same group id for bidirectional sync
group.id=region2-group
external.id=region2-id
instance.id=region2-instance

# URL where this node listens
sync.url=http://172.17.0.3:31415/sync/region2
# Accept registrations?
registration.enabled=false
# Where to registrate this node (empty if this is the first=root)
registration.url=http://172.17.0.2:31415/sync/main
# Automatically register new nodes when they request it.
# If this is false, accept the registration requests using "symadmin open-registration" command.
#auto.registration=true

job.routing.period.time.ms=5000
job.push.period.time.ms=3000
job.pull.period.time.ms=3000

# When this node sends an initial load of data to another node, first send table create scripts.
# Create tables if not exists in this node?
initial.load.create.first=true