apiVersion: batch/v1
kind: CronJob
metadata:
  name: ejemplo-cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: contenedor
              image: busybox
              command: ["echo", "Esta tarea se ejecuta diariamente a medianoche"]
          restartPolicy: OnFailure